import { DefaultHeadTag } from '@/ui/defaultHeadTag';

export default function Head() {
  return (
    <>
      <DefaultHeadTag />
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
